//
//  DeliveryListModels.swift
//  Deliveries
//
//  Created by Pouya Ghasemi on 6/21/19.
//  Copyright (c) 2019 Deliveries. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RealmSwift


enum DeliveryList
{
    enum FetchData
    {
        struct Request {
            var limit: Int!
            var offset: Int!
        }
        struct Response {
            var state: RequestState<[Delivery], ErrorModel >
        }
        struct ViewModel {
            var state: RequestState<[Delivery], ErrorModel >
        }
    }
    enum CacheData
    {
        struct Request {
            
        }
        struct Response {
            var deliveries: Results<Delivery_realm>?
        }
        struct ViewModel {
            var deliveries: [Delivery]?
        }
    }
    
}
