//
//  DeliveryPagePresenter.swift
//  Deliveries
//
//  Created by Pouya Ghasemi on 6/21/19.
//  Copyright (c) 2019 Deliveries. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DeliveryPagePresentationLogic
{
    func presentPassedData(response: DeliveryPage.PassedData.Response)
}

class DeliveryPagePresenter: DeliveryPagePresentationLogic
{
    weak var viewController: DeliveryPageDisplayLogic?
    
    func presentPassedData(response: DeliveryPage.PassedData.Response)
    {
        let viewModel = DeliveryPage.PassedData.ViewModel(delivery: response.delivery)
        viewController?.displayPassedData(viewModel: viewModel)
    }
}
