//
//  DeliveryPageModels.swift
//  Deliveries
//
//  Created by Pouya Ghasemi on 6/21/19.
//  Copyright (c) 2019 Deliveries. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum DeliveryPage
{
  
  enum PassedData
  {
    struct Request
    {
    }
    struct Response
    {
        var delivery: Delivery?
    }
    struct ViewModel
    {
        var delivery: Delivery?
    }
  }
}
