//
//  DeliveryPageInteractor.swift
//  Deliveries
//
//  Created by Pouya Ghasemi on 6/21/19.
//  Copyright (c) 2019 Deliveries. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DeliveryPageBusinessLogic
{
    func getPassedData(request: DeliveryPage.PassedData.Request)
}

protocol DeliveryPageDataStore
{
    var delivery: Delivery? { get set }
}

class DeliveryPageInteractor: DeliveryPageBusinessLogic, DeliveryPageDataStore
{
    var presenter: DeliveryPagePresentationLogic?
    var delivery: Delivery?
    
    func getPassedData(request: DeliveryPage.PassedData.Request)
    {
        let response = DeliveryPage.PassedData.Response(delivery: delivery)
        self.presenter?.presentPassedData(response: response)
    }
    
}
